package set

const (
	SET_UPDATE              = "SET_UPDATE"
	UPDATE_DATA             = "UPDATE_DATA"
	FAILURE                 = "FAILURE"
	FAILURE_DATA            = "FAILURE_DATA"
	FAILURE_FLAG            = "FAILURE_FLAG"
	VALIDATE_PUT            = "VALIDATE_PUT"
	PATH_PARAMETERS         = "PATH_PARAMETERS"
	PUT_CHECK_IF_SET_EXISTS = "PUT_CHECK_IF_SET_EXISTS"
)
