package attributes

const (
	ATTRIBUTE_UPDATE        = "ATTRIBUTE_UPDATE"
	UPDATE_DATA             = "UPDATE_DATA"
	FAILURE                 = "FAILURE"
	FAILURE_DATA            = "FAILURE_DATA"
	FAILURE_FLAG            = "FAILURE_FLAG"
	VALIDATE_PUT            = "VALIDATE_PUT"
	PATH_PARAMETERS         = "PATH_PARAMETERS"
	PATH_DECISION           = "PATH_DECISION"
	ATTRIBUTE_OPTION_UPDATE = "ATTRIBUTE_UPDATE"
	PUT_CHECK_VALUE_EXIST   = "PUT_CHECK_VALUE_EXIST"
	PUT_CHECK_IF_EXISTS     = "PUT_CHECK_IF_EXISTS"

	// Pool constants
	ATTRIBUTE_UPDATE_POOL_SIZE   = 2
	ATTRIBUTE_UPDATE_QUEUE_SIZE  = 100
	ATTRIBUTE_UPDATE_RETRY_COUNT = 3
	ATTRIBUTE_UPDATE_WAIT_TIME   = 100
)
