package put

import ()

const (
	SELLER_UPDATE                    = "SELLER_UPDATE"
	SELLER_UPDATE_POOL_SIZE          = 2
	SELLER_UPDATE_QUEUE_SIZE         = 5
	SELLER_UPDATE_WAIT_TIME          = 500
	SELLER_UPDATE_RETRY_COUNT        = 5
	UPDATE_ERP                       = "UPDATE_ERP"
	UPDATE_ERP_POOL_SIZE             = 2
	UPDATE_ERP_QUEUE_SIZE            = 5
	UPDATE_ERP_WAIT_TIME             = 100
	UPDATE_ERP_RETRY_COUNT           = 5
	PRODUCT_INAVLIDATION             = "PRODUCT_INAVLIDATION"
	PRODUCT_INAVLIDATION_POOL_SIZE   = 2
	PRODUCT_INAVLIDATION_QUEUE_SIZE  = 5
	PRODUCT_INAVLIDATION_WAIT_TIME   = 100
	PRODUCT_INAVLIDATION_RETRY_COUNT = 5
	ORG_UPDATE_DATA                  = "ORG_UPDATE_DATA"
	PUT_FAILURE                      = "PUT_FAILURE"
	FAILURE_DATA                     = "FAILURE_DATA"
	VALIDATE_SELLER_PUT              = "VALIDATE_SELLER_PUT"
)
