package constants

const (
	REQUEST            = "REQUEST"
	REQUEST_CONTEXT    = "REQUEST_CONTEXT"
	REQUEST_BODY_PARAM = "REQUEST_BODY_PARAM"
	REQUEST_PATH_PARAM = "REQUEST_PATH_PARAMETER"

	RESPONSE                = "RESPONSE"
	RESPONSE_META_DATA      = "RESPONSE_META_DATA"
	RESPONSE_DATA           = "RESPONSE_DATA"
	RESPONSE_STATUS         = "RESPONSE_STATUS"
	RESPONSE_HEADERS_CONFIG = "RESPONSE_HEADERS_CONFIG"
	API_RESPONSE            = "API_RESPONSE"

	APPERROR = "APPERROR"

	HTTPVERB = "HTTPVERB"
	URI      = "URI"

	BUCKETID = "BUCKETID"

	RESOURCE = "RESOURCE"
	VERSION  = "VERSION"
	ACTION   = "ACTION"

	RESULT = "RESULT"

	USER_ID        = "USER_ID"
	SESSION_ID     = "SESSION_ID"
	AUTHTOKEN      = "AUTHTOKEN"
	USER_AGENT     = "USER_AGENT"
	HTTP_REFERRER  = "HTTP_REFERRER"
	BUCKETS_LIST   = "BUCKETSLIST"
	REQUEST_ID     = "REQUEST_ID"
	TRANSACTION_ID = "TRANSACTION_ID"

	FIELD_SEPARATOR     = ","
	KEY_VALUE_SEPARATOR = ":"

	HEALTHCHECKAPI    = "HEALTHCHECK"
	HEALTH_CHECK_LIST = "HEALTH_CHECK_LIST"
)

const (
	SORT_ASC  = "asc"
	SORT_DESC = "desc"
)

//constant for buckets and their values
const (
	ORCHESTRATOR_BUCKET_KEY           = "Algo"
	ORCHESTRATOR_BUCKET_DEFAULT_VALUE = "Old"
	ORCHESTRATOR_BUCKET_NEW_ALGO      = "New"
)

// constant for jabong headers
const (
	JABONG_USER_ID        = "X-Jabong-UserId"
	JABONG_SESSION_ID     = "X-Jabong-SessionId"
	JABONG_REQUEST_ID     = "X-Jabong-Reqid"
	JABONG_TRANSACTION_ID = "X-Jabong-Tid"
)

// constant for monitor
const (
	MONITOR_CUSTOM_METRIC_PREFIX = "monitor_custom_metric"
)
