package attributes

const (
	ATTRIBUTE_INSERT        = "ATTRIBUTE_INSERT"
	INSERT_DATA             = "INSERT_DATA"
	MONGO_INSERT            = "MONGO_INSERT"
	FAILURE                 = "FAILURE"
	FAILURE_DATA            = "FAILURE_DATA"
	FAILURE_FLAG            = "FAILURE_FLAG"
	VALIDATE_POST           = "VALIDATE_POST"
	PATH_PARAMETERS         = "PATH_PARAMETERS"
	PATH_DECISION           = "PATH_DECISION"
	ATTRIBUTE_OPTION_INSERT = "ATTRIBUTE_OPTION_INSERT"
	POST_CHECK_IF_EXISTS    = "POST_CHECK_IF_EXISTS"
	POST_CHECK_VALUE_EXIST  = "POST_CHECK_VALUE_EXIST"
	POST_GET_OPTION_SEQ     = "POST_GET_OPTION_SEQ"
	POST_GET_SET_DATA       = "POST_GET_SET_DATA"
	POST_CHECK_SET_EXISTS   = "POST_CHECK_SET_EXISTS"
	POST_SET_DATA           = "POST_SET_DATA"

	// Pool constants
	ATTRIBUTE_CREATE_POOL_SIZE   = 2
	ATTRIBUTE_CREATE_QUEUE_SIZE  = 100
	ATTRIBUTE_CREATE_RETRY_COUNT = 3
	ATTRIBUTE_CREATE_WAIT_TIME   = 100
)
