package get

import ()

const (
	SELLER_GET                    = "SELLER_GET"
	SELLER_GET_ONE                = "SELLER_GET_ONE"
	SELLER_GET_ALL                = "SELLER_GET_ALL"
	SELLER_SEARCH                 = "SELLER_SEARCH"
	MONGO_GET                     = "MONGO_GET"
	MONGO_GET_ALL                 = "MONGO_GET_ALL"
	MONGO_SEARCH_IDS              = "MONGO_GET_SEARCH_IDS"
	MONGO_SEARCH                  = "MONGO_SEARCH"
	MONGO_GET_SELLER_SEARCH_COUNT = " MONGO_GET_SELLER_SEARCH_COUNT"
	MONGO_GET_SELLER_COUNT        = "MONGO_GET_SELLER_COUNT"
	GET_ONE                       = "GET_ONE"
	GET_SEARCH                    = "GET_SEARCH"
	UPDATE_COMMISSIONS            = "UPDATE_COMMISSIONS"
	SELLER_SET_CACHE              = "SELLER_SET_CACHE"
	SELLER_GET_FROM_CACHE         = "SELLER_GET_FROM_CACHE"
	SELLER_GET_FROM_CACHE_ACTUAL  = "SELLER_GET_FROM_CACHE_ACTUAL"
	SELLER_GET_BATCH_CACHE        = "SELLER_GET_BATCH_CACHE"
)
