package attributes

const (
	GET_ONE         = "_ATTRIBUTE_GET_ONE_"
	GET_ALL         = "_ATTRIBUTE_GET_ALL_"
	GET_SEARCH      = "_ATTRIBUTE_GET_SEARCH_"
	QUERY_DECISION  = "_ATTRIBUTE_QUERY_DECISION_"
	PATH_DECISION   = "_ATTRIBUTE_PATH_DECISION_"
	PATH_PARAMETERS = "_ATTRIBUTE_PATH_PARAMETERS_"
	ATTRIBUTES      = "attributes"
	QUERY_PARAM     = "global"
	GET_BY_ID       = "_ATTRIBUTE_GET_ID_"
)

// Datadog constants
const (
	CUSTOM_ATTRIBUTE_GET_ALL = "_CUSTOM_ATTRIBUTE_GET_ALL_"
	CUSTOM_ATTRIBUTE_GET_ONE = "_CUSTOM_ATTRIBUTE_GET_ONE_"
)
