package set

const (
	GET_ONE                  = "_ATTRIBUTESETS_GET_ONE_"
	GET_ALL                  = "_ATTRIBUTESETS_GET_ALL_"
	GET_SEARCH               = "_ATTRIBUTESETS_GET_SEARCH_"
	PATH_PARAMETERS          = "_PATH_PARAMETERS"
	ATTRIBUTES               = "attributes"
	QUERY_PARAM              = "global"
	PATH_DECISION            = "_PATH_DECISION_"
	GET_ALL_SETS             = "_ATTRIBUTESETS_GET_ALL_"
	GET_SET_BY_ID            = "_ATTRIBUTESETS_GET_BY_ID_"
	GET_ATTRIBUTES_BY_SET_ID = "_ATTRIBUTESETS_GET_ATTRIBUTES_BY_SET_ID_"
	GET_ATTRIBUTES           = "_ATTRIBUTESETS_GET_ATTRIBUTES_"
	GET_ATTRIBUTE_BY_ID      = "_ATTRIBUTESETS_GET_ATTRIBUTE_BY_ID_"
	GET_ATTRIBUTE_BY_NAME    = "_ATTRIBUTESETS_GET_ATTRIBUTE_BY_NAME_"
	GET_ALL_ATTRIBUTES       = "_ATTRIBUTESETS_GET_ALL_ATTRIBUTES_"
	GET_SET_WITH_ATTRIBUTES  = "_ATTRIBUTESETS_GET_WITH_ATTRIBUTES_"
	ATTRIBUTE_PRODUCT_TYPE   = "config"
)

// Datadog Constants

const (
	CUSTOM_ATTRIBUTESETS_GET_ALL = "_CUSTOM_ATTRIBUTESETS_GET_ALL_"
	CUSTOM_ATTRIBUTESETS_GET_ONE = "_CUSTOM_ATTRIBUTESETS_GET_ONE_"
)
