package commissions

import ()

const (
	COMMISSION_FAILURE      = "COMMISSION_FAILURE"
	SELLER_GET_COMMISSION   = "SELLER_GET_COMMISSION"
	VALIDATE_GET_COMMISSION = "VALIDATE_GET_COMMISSION"
	GET_SEARCH              = "GET_SEARCH"
	UPDATE_COMMISSIONS      = "UPDATE_COMMISSIONS"
)
