package post

import ()

const (
	SELLER_INSERT             = "SELLER_INSERT"
	SELLER_INSERT_POOL_SIZE   = 1000
	SELLER_INSERT_QUEUE_SIZE  = 20000
	SELLER_INSERT_WAIT_TIME   = 100
	SELLER_INSERT_RETRY_COUNT = 5
	ORG_DATA                  = "ORG_DATA"
	POST_FAILURE              = "POST_FAILURE"
	FAILURE_DATA              = "FAILURE_DATA"
	VALIDATE_SELLER_POST      = "VALIDATE_SELLER_POST"
)
